## Задание на повторение материала

In [4]:
import numpy as np

**task 1

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [9]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


**task 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [13]:
ar1 = a.reshape(3, 4)
print(ar1)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [14]:
ar2 = a.reshape(4, 3)
print(ar2)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [15]:
ar3 = a.reshape(2, 6)
print(ar3)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [16]:
ar4 = a.reshape(6, 2)
print(ar4)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [25]:
ar5 = a.reshape(12, 1)
print(ar5)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


**task 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [27]:
arr1 = a.reshape(2, -1)
print(arr1)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [29]:
arr2 = a.reshape(3, -1)
print(arr2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [37]:
arr3 = a.reshape(12, -1)
print(arr3)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [31]:
arr4 = a.reshape(-1, 2)
print(arr4)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [36]:
arr5 = a.reshape(-1, 3)
print(arr5)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


**task 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [ ]:
Да

**task 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [49]:
x = np.random.randn(3, 4)
print(x)
x.size

[[ 0.143115    0.95088483  1.93252348 -0.52241131]
 [ 0.06763634 -0.45753628  0.39955454 -1.08315528]
 [ 0.09553609 -1.89418788 -1.19439808  1.50791691]]


12

In [50]:
x1 = x.flatten()
print(x1)
x.size

[ 0.143115    0.95088483  1.93252348 -0.52241131  0.06763634 -0.45753628
  0.39955454 -1.08315528  0.09553609 -1.89418788 -1.19439808  1.50791691]


12

**task 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [39]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


**task 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [52]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


разницы нет...

**task 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [53]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
print(c)
c.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

**task 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [60]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [61]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [63]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [64]:
B = A.dot(At)
print(B)
B.shape

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


(4, 4)

In [65]:
d = np.linalg.det(B)
print(d)

0.0


Так как определитель матрицы равен 0, высчитать обратную матрицу невозможно

**task 10

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [67]:
np.random.seed(42)

**task 11

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [68]:
c = np.random.randint(0, 16, 16)
print(c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


**task 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [69]:
C = c.reshape(4, 4)
print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [70]:
D = B + C * 10
print(D)

[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [71]:
d = np.linalg.det(D)
print(d)

-28511999.999999944


In [72]:
r = np.linalg.matrix_rank(B)
print(r)

2


In [73]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


In [74]:
print(D.dot(D_inv))

[[ 1.00000000e+00 -8.88178420e-16 -8.88178420e-16  1.33226763e-15]
 [ 2.22044605e-16  1.00000000e+00 -8.88178420e-16  8.88178420e-16]
 [ 0.00000000e+00 -5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -3.33066907e-16  0.00000000e+00  1.00000000e+00]]


**task 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [75]:
print(D_inv)

[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


In [76]:
D_inv = np.where(D_inv < 0, 0, 1)
print(D_inv)

[[1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]]


In [77]:
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [78]:
print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [79]:
E = np.where(D_inv > 0, B, C)
print(E)

[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
